set(spencer_detected_person_association_MESSAGE_FILES "")
set(spencer_detected_person_association_SERVICE_FILES "/home/meam/wheelchair_ws/src/spencer_people_tracking/detection/spencer_detected_person_association/srv/LookupTrackId.srv;/home/meam/wheelchair_ws/src/spencer_people_tracking/detection/spencer_detected_person_association/srv/LookupTrackIds.srv")
